### ISSUE TITLE
misleading translation

### ISSUE THREAD

**Issue by grelf111** [shopware/devdocs#1020]
Shopware 5 snippet management 
- Understanding snippet handling
-> bullet point list

now: If the snippet is not present in the database, has a default value set and ....
better: If the snippet is not present in the database, **has set a default value** and ....

now: If the snippet is not present in the .ini file, has a default value set and ....
better: If the snippet is not present in the .ini file,  **has set a default value** and

**Comment by mitelg** [comment]
hey @grelf111 
thanks for pointing this out :+1: would you mind creating a PR fort that? :blush: 
https://github.com/shopware/devdocs/blob/master/source/designers-guide/snippets/index.md#understanding-snippet-handling

**Comment by bneumann97** [comment]
@mitelg I've mad a PR for that. https://github.com/shopware/devdocs/pull/1043

**Comment by mitelg** [comment]
fixed with https://github.com/shopware/devdocs/commit/104023a69b787d6d9bd0f32cb044c68aa66bab28
