### ISSUE TITLE
Clarify minimal transaction isolation level

### ISSUE THREAD

**Issue by jonashrem** [shopware/devdocs#1064]
## Description
MySQL supports multiple Isolation Levels for InnoDB which are set to "REPEATABLE READ" by default. I would like to know which of those levels are supported by shopware, as Isolation Level with lesser consistent, can always perform better in some situations.

## Possible solutions

I would like to know which of the Isolation Levels ( https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html#isolevel_read-committed ) can safely be used with (stock) shopware.

## Additional information

See also:

*  https://mydbops.wordpress.com/2018/06/22/back-to-basics-isolation-levels-in-mysql/ 
* https://en.wikipedia.org/wiki/Isolation_(database_systems)

**Comment by bcremer** [comment]
@mitelg 
To be honest, that sounds like a very legit question and is not individual at all and should documented in the requirements document.

@jonashrem 
I'd not run any other isolation level than the default REPEATABLE READ as this is the default level that is used for all automated and manual tests as far as I can tell from the source.

**Comment by mitelg** [comment]
@bcremer to be honest I have never heard a question like this before. 

but maybe as I am not that good into databases, I considered this as a very individual question :see_no_evil: 
sorry for that and thank you very much for answering :slightly_smiling_face: :+1:

**Comment by mitelg** [comment]
@jonashrem okay, after reading a bit through the posted articles, I would also suggest the default `REPEATABLE READ` 

and as @bcremer already stated, other isolation levels are not used and tested by us, so using them goes to own risk. 

I will have a look if I could put it somewhere sensible :+1: 

thank you all :wave:

**Comment by bcremer** [comment]
@mitelg No worries, thanks for re-considering.

**Comment by mitelg** [comment]
thank you, for having Shopware still in mind :hugs: :blue_heart:

**Comment by bcremer** [comment]
![Harry-Potter Always](https://c.tenor.com/n3YgVsxkhNEAAAAC/hp-harry-potter.gif)
