### ISSUE TITLE
How to setup ESD in Shopware 6 ?

### ISSUE THREAD

**Issue by milindsingh** [shopware/devdocs#1066]
I am able to find in Shopware 5, How to do it in 6?
https://docs.shopware.com/en/shopware-5-en/products-and-categories/esd#settings-and-configuration

**Comment by shyim** [comment]
Its currently not implemented in Shopware 6. 
For more information see the issue https://issues.shopware.com/issues/NEXT-3519

**Comment by ChristopherDosin** [comment]
We have build an ESD plugin for those who are interested in: 
https://store.shopware.com/en/sas9155591716916/esd/downloads-for-shopware-6.html
