### ISSUE TITLE
Debug-page seems out of date

### ISSUE THREAD

**Issue by Squall83** [shopware/devdocs#1074]
https://github.com/shopware/devdocs/blob/master/source/developers-guide/debugging/index.md
The ExtJS part of this page seems to be outdated, because there is no "ext-all-debug.js" file anymore. There is a "ext-all-dev.js" file, but if i include that one, nothing changes.

At https://docs.shopware.com/en/shopware-5-en/plugins/core-plugins i found the following information:

> We have described debugging in detail in our developer documentation in the article Debugging Shopware. **There you will also find the functionality of the debug plugin**.

There i found the following:
> Shopware also ships with a plugin called "debug" which will allow you to print out template assignments to the console tab of your developer tools window. Just install the plugin using Shopware's plugin manager, configure it to your needs and reload the page.

I installed, configured, cleared cache, reloaded, and nothing happens again. Is there maybe more to do? Does this plugin creates files anywhere?

![grafik](https://user-images.githubusercontent.com/8791670/82906599-cdb62100-9f65-11ea-8ebf-fd3934f0c4df.png)

>In many cases, you will have no alternative but to debug using console.log() calls in your Javascript code. The following list should help you narrow down the error

I am running this guide (https://developers.shopware.com/developers-guide/backend-components/associations/#manytomany-associations-products-&-categories) and have no idea where to output something. Where to put the debug in extJS? and what to put inside?
e.g.
```
Ext.define('Shopware.apps.SwagProductAssoc.view.detail.Product', {
    extend: 'Shopware.model.Container',
    alias: 'widget.product-detail-container',
    padding: 20,

    configure: function() {
        console.log(categories); /** is that correct? */
        return {
            controller: 'SwagProductAssoc',
            associations: [ 'categories' ]
        };
    }
});
```

Clearly it is my fault that i am not familar with Shopware and ExtJS, but it would be great if the docs could help me out a bit.

PS: i apologize if my issue seems aggressive, i tried to be objectively.

**Comment by mitelg** [comment]
hey @Squall83 
you are right, we changed this with Shopware 5.6
Have a look here: https://github.com/shopware/shopware/blob/5.6/UPGRADE-5.6.md#extjs-developer-mode

This is the according commit: https://github.com/shopware/shopware/commit/6447c06bbd520eeec3098cbf97c806b5049a3df0

@shyim hopp, hopp! rewrite the docs! :smile:
