### ISSUE TITLE
wrong callback name in the description under the code example

### ISSUE THREAD

**Issue by kokoyroy** [shopware/devdocs#1092]
As defined in getSubscribedEvents the callback is called **onFrontendPostDispatch**. It takes an Enlight_Controller_ActionEventArgs object as parameter, which holds context about the event - in this case the context of the controller that has been executed.

**onFrontendPostDispatch** has to be **onPostDispatch** as in code above

**Comment by mitelg** [comment]
hey @kokoyroy 
on which page do you mean?

**Comment by kokoyroy** [comment]
https://developers.shopware.com/developers-guide/plugin-quick-start/#subscriber-classes

**Comment by mitelg** [comment]
then this would be the file to edit: https://github.com/shopware/devdocs/blob/master/source/developers-guide/plugin-quick-start/index.md#subscriber-classes

maybe you like to create a PR? :blush:

**Comment by kokoyroy** [comment]
what is the pr? i am noob :P

**Comment by mitelg** [comment]
you are able to make change suggestions to the documentation code itself :blush: 

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
