### ISSUE TITLE
java sdk not installed by default

### ISSUE THREAD

**Issue by kirilgicevski** [shopware/devdocs#139]
Hello guys. Great work !!! I just had one small issue. whenever I've runned  "ant build-unit" i had the problem that tools.jar was not there. I have solved this with just installing  Java SDK (sudo apt-get install openjdk-7-jdk). I guess it should have been there at first place.

**Comment by bcremer** [comment]
Thank you @kirilgicevski, we will add this as a note.
Instead of a full JDK the package `openjdk-7-jre-headless` should be enough. It has the most minimal dependencies to get ant running.
