### ISSUE TITLE
How create or add product from plugin

### ISSUE THREAD

**Issue by aceneeraj** [shopware/devdocs#198]
I am new in shopware , i am creating a plugin that is based on canvas greeting card designing and  i want to create product using my plugin , So how to achieve  this from plugin ,
Every things are going well in my plugin but i stacked here for the same.
So please share some piece of code or any  document that help me to achieve this task.
Thanks 
Neeraj

**Comment by tiagojsag** [comment]
Hi, @aceneeraj 

From what I understand, you are having issues implementing your custom Shopware plugin. This github project covers only the Shopware documentation. If you have questions regarding Shopware itself or you need free support from the community, please use the forums: http://en.forum.shopware.com/

closing

**Comment by dnoegel** [comment]
Hi Tiago was to fast, was about to write the same :)

Just try the forum, I will have a look later one :+1:

**Comment by aceneeraj** [comment]
Ok i will post this problem there. 
Thanks you so much for reply
