### ISSUE TITLE
Sync Folder

### ISSUE THREAD

**Issue by ededagic** [shopware/devdocs#207]
Is there any reason not using sync folders, which are created between host and virtual machine, instead of deploying changes with ftps and phpstorm ?

**Comment by bcremer** [comment]
It's mostly because we experienced bad performance when using sync folders. You can work around this issue a bit by excluding cache directories etc. from syncing but for best performance we still use the sftp deploy workflow with phpstorm.

**Comment by ededagic** [comment]
ok. Thnx. Meanwhile i pointed out, that using sftp solves another problem i used to have, which is the need for changing ownership and permissions on files. With SFTP there are two copies, my local and remote copy, with no need of changing any file ownership
