### ISSUE TITLE
Swag Controller 

### ISSUE THREAD

**Issue by daslicht** [shopware/devdocs#268]
Hi,
I just started with Shopware Dev. 

I put the [SwagController] (https://developers.shopware.com/exampleplugins/SwagSloganOfTheDay.zip) example in /local/frontend ,activated it in the backend, but the following route returns nothing special :
```
http://shopware.site/frontend/test/index
```

**Comment by Asabs** [comment]
Hi.
The link is dead.

**Comment by daslicht** [comment]
fixed
source: 
https://developers.shopware.com/developers-guide/plugin-quick-start/

**Comment by Asabs** [comment]
The SwagSloganOfTheDay plugin does not register a custom controller.
If you want to register a custom controller look here: https://developers.shopware.com/developers-guide/controller/
For Learning Shopware I would recommend the Shopware 4 docs, they are more exhaustive and still quite relevant, but in german.
