### ISSUE TITLE
Elasticsearch version mismatch

### ISSUE THREAD

**Issue by LarsFronius** [shopware/devdocs#314]
According to https://github.com/shopware/devdocs/blob/3d3a138829e390afc7ba88fd227629d21a07073a/source/sysadmins-guide/elasticsearch-setup/index.md
only 1.6 is officially supported.
However, according to https://github.com/shopware/shopware/blob/5.1/composer.json#L41 Shopware is running the 2.2 client library.
We successfully ran on 2.3.3 already.

Thus I wonder whether the documentation is just outdated in this case and what is generally considered best practice for the Elasticsearch setup on Shopware 5.1/5.2?

**Comment by bcremer** [comment]
As I read the version matrix here https://github.com/elastic/elasticsearch-php/tree/v2.2.0#version-matrix Elasticsearch Version 1.6 should be considered the minimum supported version, not the concretely required version.

**Comment by bcremer** [comment]
Correction. Since we also depend on [ongr-io/ElasticsearchDSL](https://github.com/ongr-io/ElasticsearchDSL/tree/v2.0.2#elasticsearchdsl) we require Elasticsearch 2.0 or newer.

**Comment by bcremer** [comment]
Fix with #319.
