### ISSUE TITLE
OneToMany associations don't work

### ISSUE THREAD

**Issue by codekeller-official** [shopware/devdocs#447]
The last part covering "OneToMany" associations is not complete and therefor useless. It leaves out the detail window of variants and there is no example code anywhere to be found. Shopware itself never uses the "extend: 'Shopware.store.Association'" code that is given in the tutorial. All questions about this issue on the community board are unanswered. I can manage to display the data of a variant in a detail window, but I can't save it ("Cannot read property indexOf of undefined" in urlAppend method of ext-app.js). How do you manage to get variants to work?

**Comment by OliverSkroblin** [comment]
Hi,
the backend components handles only the first level of association with all crud operations. The example only shows that it is possible to load big association on demand. 
To working with a sub-association-window you have to handle the foreign key by yourself. In this case it means, before you create a new variant over the window or an row editing, you have to set the productId property with the current record id.
