### ISSUE TITLE
 devdocs/source/developers-guide/risk-rules/index.md not working with 5.2.10 and attached zip error

### ISSUE THREAD

**Issue by lhwparis** [shopware/devdocs#458]
The guide to add a custom risk rule is not working for me with shopware 5.2.10
1. the attached file uses "Frontend" as folder but its declared as "Backend" in the bootstrap.php
2. if i change the folder and upload the plugin there is no rule added to the risk management so the tutorial and attached example are not woking for me

**Comment by timomayer** [comment]
I don't think this is fixed at all since when I use the zip as is it is not working in shopware 5. 2.10 the rest rule is not appearing in the drop down.

**Comment by lhwparis** [comment]
I don't think this is fixed at all since when I use the zip as is it is not working in shopware 5. 2.10 the rest rule is not appearing in the drop down.

**Comment by lhwparis** [comment]
Does someone have an idea why it is not working?  Can not figure it out :( If I know the problem I am happy to send a pr.

**Comment by mitelg** [comment]
hi @lhwparis 
I just tested the plugin on a current Shopware version and had no problems. What is exactly your problem?

**Comment by lhwparis** [comment]
Sorry my fault, tested it again and it works now dont know what was the problem when i tested it after you merged the PR.
