### ISSUE TITLE
Atom feed for blog posts does not work

### ISSUE THREAD

**Issue by vintagesucks** [shopware/devdocs#483]
https://developers.shopware.com/blog/atom.xml

> This page contains the following errors:
> `error on line 1 at column 33: XML declaration allowed only at the start of the document`
> Below is a rendering of the page up to the first error.

**Comment by bcremer** [comment]
Fixed with commit https://github.com/shopware/devdocs/commit/68e40ae6c954b08534dd433de859b4ac1d9a8e2d.

Thanks for reporting :+1:
