### ISSUE TITLE
Nginx auth proxy not working 

### ISSUE THREAD

**Issue by krugar100** [shopware/devdocs#501]
Hi @bcremer ,

This is regarding the [2015-03-02-sso-with-nginx-auth_request.md](https://github.com/shopware/devdocs/blob/master/source/blog/_posts/2015-03-02-sso-with-nginx-auth_request.md).
In this part of nginx.conf
```
server {
    ...
    error_page 401 = @error401;
    location @error401 {
        return 302 https://login.example.com;
    }
}
```
What should ```login.example.com``` return and where? How does it tell nginx that user is authenticated and subsequently redirect to ```staticpage.example.com```?

PS : Similar attempt was made in [nginx-auth-proxy](https://github.com/Siecje/nginx-auth-proxy). But the authentication is not working properly. I spent hours in trying to understand what is going wrong there. [This](https://github.com/Siecje/nginx-auth-proxy/issues/1) issue contains few details about it. Can you help me in debugging this?

**Comment by bcremer** [comment]
`login.example.com` can be anything.  It's a website the user get's redirected to, if he is not yet authenticated. `login.example.com` is responsible for the actual user login and to write the cookie. If you want the user to be redirected back to `staticpage.example.com` after a successful login you could read the HTTP referer to the the exact location the user was redirected from.

**Comment by mitelg** [comment]
I will close this for now.
