### ISSUE TITLE
Incorrect icon classes (styletile)

### ISSUE THREAD

**Issue by vintagesucks** [shopware/devdocs#507]
https://developers.shopware.com/styletile/_components-icon-set.html

The following icons are missing `arrow` in their class description:

icon--right4
icon--left5
icon--down5
icon--up4
icon--right5
icon--left6
icon--down6
icon--up5
icon--right6

Example:
```
<td><i class="icon--arrow-down5"></i><br/>
    icon--down5
</td>
```

Should be:
```
<td><i class="icon--arrow-down5"></i><br/>
    icon--arrow-down5
</td>
```

**Comment by screeny05** [comment]
see https://github.com/shopware/shopware/pull/496/files

**Comment by mitelg** [comment]
fixed with https://github.com/shopware/devdocs/commit/f7f8782bdd4ebb1bf13cbee1df75c0b4b00da596
