### ISSUE TITLE
Extend Backend Article module

### ISSUE THREAD

**Issue by andrii-trush** [shopware/devdocs#518]
Cannot extend "Add item" module with new Tab. 
Trying to make by [This example](https://developers.shopware.com/developers-guide/backend-extension/#example-#2:-custom-components), but it does not work.

**Comment by mitelg** [comment]
Hi @andrii-trush 
do you have more information for us? 

If the example is wrong, please let us know! but if you are troubling to reimplement it own your own, maybe you should ask here for help :blush: :+1: 
Our [forum](https://forum.shopware.com/) or our [IRC channel](https://developers.shopware.com/contributing/irc/)

Best regards
Michael
