### ISSUE TITLE
Token delivery is very slow

### ISSUE THREAD

**Issue by Amaridian** [shopware/devdocs#555]
We have deactivated the CSRF protection due to problems in the checkout process. Now we still see a file named https://www.ourdomain.de/csrftoken loaded on every request an with weiting times of half a second. 

We are optimizing our pages on speed aspects an this one is a huge drawback. How can we get rid of that csrf call or how can we speed it up?

![image](https://cloud.githubusercontent.com/assets/3269513/25170834/2790b1d8-24ec-11e7-9e3c-1ec0f4c03296.png)

**Comment by mitelg** [comment]
Hello @Amaridian 
I think this is not the right place to ask such question :wink: This issue section should be used for issues, regarding our developer documentation. 

Problems with Shopware itself, could be reported here: https://issues.shopware.com/
If you need support you can get it via the support function in your Shopware Account, or you use our forum: https://forum.shopware.com/

Best Regards from Schöppingen
Michael Telgmann
