### ISSUE TITLE
addresses end point not retrieve customer_id or user_id (REST)

### ISSUE THREAD

**Issue by zexperto** [shopware/devdocs#628]
hello,
this "api/addresses" in REST api does not retrieve customer_id or user_id, i cannot know which address for which customer

**Comment by mitelg** [comment]
Hi @zexperto 
you are right. at the moment the GET (List) call does not contain the information about the customer. If you get one address by its ID, it contains the customer. 
If you want that behaviour changed, you could open a ticket here: https://issues.shopware.com/
