### ISSUE TITLE
Docs for REST endpoint 'addresses' states there should be a customer element in each address

### ISSUE THREAD

**Issue by mgaerber** [shopware/devdocs#750]
When I call addresses, there is no customer element

https://github.com/shopware/devdocs/blob/master/source/developers-guide/rest-api/api-resource-address/index.md

**Comment by mitelg** [comment]
@shopwareBot can someone have a look here? maybe @jenskueper ?

**Comment by mitelg** [comment]
hey @mgaerber 
the `list` query does not give you the customer data. that is correct. but the call of one single address.
I will add a note about this to the docs
