### ISSUE TITLE
Documentation for REST endpoint 'customers' lists deprecated fields 'shippings' and 'billings'

### ISSUE THREAD

**Issue by MarkusWb** [shopware/devdocs#753]
According to the [Update Guide](https://developers.shopware.com/developers-guide/shopware-5-upgrade-guide-for-developers/#account-/-registration), shippings and billings have been replaced by defaultShippingAddress and defaultBillingAddress, which have the type address.
Shipping and billing still seem to work for POST requests.

**Comment by mitelg** [comment]
hey @MarkusWb 
the keys 'billing' and 'shipping' will be used to create new objects of the kind `address`
See here: https://github.com/shopware/shopware/blob/5.3/engine/Shopware/Components/Api/Resource/Customer.php#L204

I will fix the link in the customer docs

**Comment by mitelg** [comment]
fixed with a292cccc38a58acff094f48472da77ecf8c96df7

**Comment by MarkusWb** [comment]
Still, a GET request returns the fields defaultShippingAddress and defaultBillingAddress instead of the shipping and billing used in the POST request--which led to my confusion in the first place and is highly inconsistent.
