### ISSUE TITLE
Plugin quick start guide missing implementation of SloganPrinter

### ISSUE THREAD

**Issue by felixgeyer** [shopware/devdocs#757]
Hi,

I'm using the documentation wo get started with shopware.
Therefore I followed the [plugin quick start guide](https://developers.shopware.com/developers-guide/plugin-quick-start/) to develop my first plugin.

Unfortunately the implementation of the used class/component `SloganPrinter` is not explained, or am I missing something?

**Comment by mitelg** [comment]
Hi @felixgeyer 

you can download the example plugin here: https://developers.shopware.com/exampleplugins/SwagSloganOfTheDay.zip

the `SloganPrinter` just returns random sentences

**Comment by felixgeyer** [comment]
Hi @mitelg,

thanks for providing the source code of the demo plugin.

Nevertheless I'd be happy if the documentation is updated, so the tutorial is complete. 
Otherwise, the documentation is frustrating for developers who are new to shopware.
