### ISSUE TITLE
Wrong maths - This doesn't add up

### ISSUE THREAD

**Issue by bodiski** [shopware/devdocs#768]
If a single page takes 250ms (milliseconds) to load surely 4 pages would take 1 second, not 1 minute, right?
250ms x 4 = 1000ms = 1s

So 400 page loads would take 100 seconds as opposed to 1h.

![image](https://user-images.githubusercontent.com/3490727/34487309-b72e2a32-efcb-11e7-93c7-4236a4f4e539.png)

**Comment by JanPietrzyk** [comment]
whuuu, embarassing... Thanks for the info, should have thought twice while writing the table. I will prepare a pull request that fixes the issue.

**Comment by mitelg** [comment]
@JanPietrzyk push :wink:

**Comment by mitelg** [comment]
fixed with 5be1ef4
