### ISSUE TITLE
sudo apt-get install nodejs-legacy problem

### ISSUE THREAD

**Issue by mostafa-hisham** [shopware/devdocs#786]
we shold change this command
sudo apt-get install nodejs-legacy npm
to:
sudo apt-get install nodejs npm

cuz nodejs-legacy install node v4.2 and to complete the grunt installation we need node v4.5 pr above

**Comment by mitelg** [comment]
@klarstil what do you say about that?

**Comment by klarstil** [comment]
@mostafa-hisham You're right about that, thanks for pointing it out

**Comment by mostafa-hisham** [comment]
No problem
