### ISSUE TITLE
Request for higher quality Entity Relationship diagram

### ISSUE THREAD

**Issue by rohithmeethal** [shopware/devdocs#787]
Please add higher quality entity relationship diagram, as the current pdf looses quality when zoomed to 100%, with difficulty to read the text.

https://developers.shopware.com/developers-guide/entity-relationship-model/

**Comment by oktupol** [comment]
This must be an issue of your pdf reader. I can zoom in just fine

![ERD](https://imgur.com/a/Gpy1u)

**Comment by rohithmeethal** [comment]
I guess thats the case, ubuntu default viewer and firefox shows blurry version while chrome does it all right , Thank you .
