### ISSUE TITLE
Sample Plugin SwagPluginSystem is missing a tag

### ISSUE THREAD

**Issue by Isengo1989** [shopware/devdocs#788]
I was trying to figure out why the template extension does not work - the services.xml is missing:
`            <tag name="shopware.event_subscriber"/>
`
after
`            <argument type="service" id="template"/>
`
in **custom/plugins/SwagPluginSystem/Resources/services.xml**

it is [documented](https://developers.shopware.com/developers-guide/example-plugin/#register-template-first) - but missing in the files

**Comment by mitelg** [comment]
hey @Isengo1989 thanks for the hint. fixed with 56463b7
