### ISSUE TITLE
Customer filter missing in docs

### ISSUE THREAD

**Issue by pquerner** [shopware/devdocs#804]
Is it possible to filter customers, like only get inactive customers? 
Its missing in the docs, but its working. (Shopware 5.3.4)

```
'filter' => [
                            [
                                'property' => 'active',
                                'value' => false
                            ]
                        ]
```

Its also missing the customer model.

**Comment by mitelg** [comment]
hey @pquerner 
filtering does work the same for all resources, see here https://developers.shopware.com/developers-guide/rest-api/#filter

**Comment by pquerner** [comment]
Yes, but it says "look at the models to see what you can filter." And the customer models isnt there to look at.

**Comment by mitelg** [comment]
hey @pquerner the regarding doctrine models could be found here https://github.com/shopware/shopware/tree/5.3/engine/Shopware/Models

**Comment by pquerner** [comment]
Yes, thats how I found out.
```
The available properties can be extracted from the Shopware models below.
```
When I go to the models page
https://developers.shopware.com/developers-guide/rest-api/models/
The Customer model is missing.
So there is no way of getting the properties of a customer model, from the Docs page. Just by looking at the sourcecode.

**Comment by mitelg** [comment]
ah now I get it :blush: 
you are totally right. I will fix that :+1:
