### ISSUE TITLE
No Javascript Documentation, no Future

### ISSUE THREAD

**Issue by chwzr** [shopware/devdocs#809]
Why the heck using the API from old and slow PHP? It makes no sense, you can write a plugin in PHP which hooks directly...

We need more Javascript snippets, since nowadays Websites are performing better when they using principles like PWA which are mainly powered by client side Javascript.. If Shopware will not provide a documentation which shows some JS Snippets, its not ready for the future of the Web.

Frameworks like Vue.js / Polymer / React / Angular are the way the best user experiences are made. And not a php generated page, which is even not accessible when offline or with poor connection... so please do your homework shopware!

**Comment by buddhaCode** [comment]
http://lmgtfy.com/?q=access+rest+api+with+vue.js

**Comment by chwzr** [comment]
i'm sure its fun since nearly all browsers have the storage API and there are other solutions like app-indexeddb-mirror and so on... 

[take a look here](https://developer.mozilla.org/de/docs/Web/API/Web_Storage_API) 

[or here...](https://www.webcomponents.org/element/PolymerElements/app-storage/elements/app-indexeddb-mirror)


in the meantime i've managed it to consume the shopware api within my backend-server. But since the api docs are not JS friendly new front-end developers wont come and make awesome front-end shopping apps with your api. 

ah forgot this: [http://lmgtfy.com/?q=progressive+web+app](http://lmgtfy.com/?q=progressive+web+app)

**Comment by mitelg** [comment]
I think issues with the API of Shopware have nothing to do with the developer documentation of Shopware. Please open a ticket here https://issues.shopware.com/ :blush: :+1: 

I will close this for now. If you have an issue with the docs, feel free to open an issue again

**Comment by chwzr** [comment]
never had a issue with the api. Read the init issue comment, it's a issue with the docs which did not have much js snippets. But feel free to let new devs stumble in the dark...

**Comment by mitelg** [comment]
ok, but I don't really understand your Problem. there is a whole category https://developers.shopware.com/designers-guide/ just for frontend and templating stuff. 

There is documentation about how to add new Javascript, how to extend existing jQuery Plugins, etc ... What exactly do you miss?
