### ISSUE TITLE
wrong extjs version documentation linked

### ISSUE THREAD

**Issue by hlb-schmidt** [shopware/devdocs#852]
shopware 5.4.2 uses extjs 4.1.0 (according to Ext.getVersion('extjs')) but documentation at https://developers.shopware.com/developers-guide/backend-components/basics/ links to http://docs.sencha.com/extjs/4.1.3/#!/api

and apparently extjs removes features even in patch versions!?

http://docs.sencha.com/extjs/4.1.0/#!/api/Ext.container.Container-method-onAdded
onAdded( container, pos )

http://docs.sencha.com/extjs/4.1.3/#!/api/Ext.container.Container-method-onAdded
onAdded( )

ps. the 2 other extjs links on that page also link to the wrong extjs version

**Comment by mitelg** [comment]
hey @hlb-schmidt 
thanks for the hint! the ExtJs version we use is 4.1.1 :smile: 
but you are right. I will fix that soon. 

And yes, ExtJs does not use SemVer and breaks things on every version...

**Comment by hlb-schmidt** [comment]
hmm, and why does `Ext.getVersion('extjs')` give 4.1.0?

**Comment by klarstil** [comment]
Hey @hlb-schmidt ,

we're always referring the core version. At the time of the build, the core was 4.1.1. and ExtJS at 4.1.0

![screen shot 2018-04-12 at 14 12 09](https://user-images.githubusercontent.com/170133/38676517-977c1b98-3e5b-11e8-8a5f-5b3b5c3c40ae.png)
