### ISSUE TITLE
sticky argument for `createGrowlMessage()` not available

### ISSUE THREAD

**Issue by voodoods** [shopware/devdocs#868]
### Problem

The postMessage API documentation indicates that there is a third argument available for `createGrowlMessage()` that allows the growl message to be sticky: https://developers.shopware.com/developers-guide/lightweight-backend-modules-api/#postmessage-api-documentation

However the current function definition does not accept such an argument, see:
https://github.com/shopware/shopware/blob/56df57575909854d2dec7fcba07500e27a3361ee/themes/Backend/ExtJs/backend/base/component/Shopware.Notification.js#L535

Instead, `createStickyGrowlMessage()` works as a separate function all by itself, see: https://github.com/shopware/shopware/blob/56df57575909854d2dec7fcba07500e27a3361ee/themes/Backend/ExtJs/backend/base/component/Shopware.Notification.js#L611

### Tested Examples

**Suggested in the docs - does not work:**
```javascript
Shopware.Notification.createGrowlMessage(
  'My title',  
  'Some description text.',
   true, // should make the growl message sticky
   false, 
   { 
      btnDetail: { 
        link: 'http://wiki.shopware.de' 
      } 
   }
);
```

**Results in:**

![bildschirmfoto 2018-06-15 um 13 58 49](https://user-images.githubusercontent.com/1707307/41466925-947998be-70a4-11e8-94d8-3121eba04a40.png)

___

**Suggested in the source code's comment - does work:**
```javascript
Shopware.Notification.createStickyGrowlMessage({
  title: 'My title',
  text: 'Some description text.',
  log: false,
  btnDetail: {
    link: 'http://wiki.shopware.de'
  }
});
```

**Results in:**

![bildschirmfoto 2018-06-15 um 13 57 06](https://user-images.githubusercontent.com/1707307/41466926-96cb9900-70a4-11e8-93dd-f396b0649c41.png)

**Comment by klarstil** [comment]
That's a good catch, thanks :) I'll take care of it and will change the documentation accordingly

**Comment by mitelg** [comment]
hey @voodoods 
the documentation you are referring to, is the documentation about the postmessage API 
https://github.com/shopware/shopware/blob/5.7/themes/Backend/ExtJs/backend/base/frame/postmessage-api.js#L506

which has only the mentioned method. afterwards this method is called: https://github.com/shopware/shopware/blob/5.7/themes/Backend/ExtJs/backend/base/component/Shopware.ModuleManager.js#L396-L412

there is differentiation between sticky or not.
