### ISSUE TITLE
Add shopware / php matrix for supported version

### ISSUE THREAD

**Issue by reConNico** [shopware/devdocs#873]
It'd be great to have a shopware/php matrix for supported php versions for each shopware version.

It could be an table with green ticks/red crosses which shows the support of php versions for each shopware version.

Ioncube supported versions should also be included in the table (deprecated above SW 5.5).

**Comment by mitelg** [comment]
there is a nice stackoverflow question, which answer this :slightly_smiling_face: :+1: 

https://stackoverflow.com/questions/62953186/shopware-5-which-shopware-version-uses-which-min-php-version
