### ISSUE TITLE
extjs links 404

### ISSUE THREAD

**Issue by hlb-schmidt** [shopware/devdocs#874]
the three extjs doc links in https://developers.shopware.com/developers-guide/backend-components/basics/ are 404

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: extjs/4.1.1/index.html
RequestId: 38D5F1773B607998
HostId: yhzi8Hsxok0Y6KiUM/QAPSWxeMOTTsVFOItwXS8cdjh6jbLa8108jBm8oq8ovVpLhBlSQS5CJSU=
```

i hope this is just temporary, cause 4.1.3 is still there, but we cant trust those cause they break the api even on minor version changes...

**Comment by mitelg** [comment]
Hey @hlb-schmidt 
thanks for the hint! It seems not to be temporary unfortunately :disappointed: 
we found the docs under a cdn link. hopefully it will last there :smile:

**Comment by mitelg** [comment]
seems to be that they are online again :see_no_evil: :smile: 
https://docs.sencha.com/extjs/4.1.1/#!/api

I will revert my changes
