### ISSUE TITLE
Wrong link on "Payment Plugin" page

### ISSUE THREAD

**Issue by lkreimann** [shopware/devdocs#906]
Found a broken link on this page: https://developers.shopware.com/developers-guide/payment-plugin/ (our plugin guides)

The broken link is https://developers.shopware.com/developers-guide/payment-plugin/plugin-guide/ (relative link in the Markdown file)

Not to sure where the user should land, when clicking the link. Would totally fix that for you, if someone would just point me to the right direction (URL) :)

**Comment by mitelg** [comment]
hey @lkreimann 
I think the link should refer to this page: https://developers.shopware.com/plugin-guide/

I will fix this in a minute. thanks for your report!
