### ISSUE TITLE
Example Zip File not working

### ISSUE THREAD

**Issue by timste** [shopware/devdocs#962]
The linked ZIP-file at the end of the article *https://developers.shopware.com/developers-guide/controller/ * is buggy in the latest SW version.

**Comment by iannacone** [comment]
+1

**Comment by iannacone** [comment]
i would add that the Teplate part [https://developers.shopware.com/developers-guide/controller/#template](here) is not working (tested v. 5.5.7)

**Comment by mitelg** [comment]
cannot reproduce
