### ISSUE TITLE
Details not visible at the Order Positions

### ISSUE THREAD

**Issue by mediagraphik** [shopware/devdocs#970]
Hello,
i have an issue with the newest SW Version and the CustomProduct plugin.
Everything works fine except the detail view of the order position.
The add field doesnt show in the details, but the request gets it.

`data: [{label: "Set Dämpfungsockel", type: "checkbox", multi: true,…},…]
0: {label: "Set Dämpfungsockel", type: "checkbox",,…}
1: {label: "Länge Kältemittelleitungen 6/10 gebördelt", type: "custom_type",…}`

type: "checkbox" is shown but not the custom field.

**Comment by mitelg** [comment]
Hey @mediagraphik 
this is the repository for our developer documentation. If you have an issue with Shopware or with one of our plugins, please use the issue tracker to report a problem: https://issues.shopware.com/
