### ISSUE TITLE
[styletile] Update

### ISSUE THREAD

**Issue by tinect** [shopware/devdocs#992]
The styletile has different content for same topic.

Generally it'll be great, if we could know, how the styletile is gerenerated. Tried to catch some bugs, ended with headache :-) Additionally for PRs it'll be more great to have styletile in seperated repo instead of branch.

Icon-Set: https://developers.shopware.com/styletile/components.html#icon-set
Icons: https://developers.shopware.com/styletile/cheatsheet.html#icons

- Icon-Set and Icons are missing the new ones, coming with 5.5.7: https://github.com/shopware/shopware/commit/9c1b277f996917c9c49016b436459079b6099f22
- Iconset has some wrong naming, See for ref.: https://github.com/shopware/devdocs/pull/991/files
- There should be just one base font, not two: 1. shopware, 2. shopware_website

Ping @mitelg @klarstil

**Comment by mitelg** [comment]
@tinect is there still a problem?

I am currently struggling in finding out, how the styletile is generated :grimacing:

**Comment by tinect** [comment]
Yes, the problem persists. You can see the icons at the end in docs not showing up.

I really don't know the stuff, too :-( but after 2,5 years no one complaining about or fixing it, we can close it? 🤔

**Comment by mitelg** [comment]
I will try to get in touch with @klarstil 

maybe we can sort it out. if this does not help, I will close the issue :see_no_evil:

**Comment by mitelg** [comment]
hey @tinect 

I found out, that the current state of the styletile was created by hand :hammer_and_wrench: :slightly_smiling_face: 

so we also need to fix things manually. means, if there is something missing or something wrong, we would highly appreciate any pull request on the [styletile branch](https://github.com/shopware/devdocs/commits/styletile) :muscle: 

for now I will close this issue and we are awaiting PRs (not necessarily only by you of course! :wink: )
